name: woerldle
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  backdrop: ^0.7.1
  latlong2: ^0.8.1
  flutter_typeahead: ^3.2.4
  shared_preferences: ^2.0.13
  flutter_polyline_points: ^1.0.0
  flutter_map: ^0.14.0
  geojson: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/countries.json
    - assets/countries.geojson
    - assets/countries/
  uses-material-design: true
