name: woerldle
description: Flutterprojekt DHBW Semester 4

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  backdrop: ^0.7.2
  latlong2: ^0.8.1
  flutter_typeahead: ^3.2.5
  shared_preferences: ^2.0.13
  flutter_polyline_points: ^1.0.0
  flutter_map: ^0.14.0
  geojson: ^1.0.0
  flutter_svg: ^1.0.3
  flutter_svg_opt: ^0.0.1
  flutter_osm_plugin: ^0.32.2
  flutter_map_marker_popup: ^2.1.2
  devicelocale: ^0.5.1
  flutter_launcher_icons: ^0.9.2
  country_codes: ^2.1.1
  fl_chart: ^0.50.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/Woerldle.png"

flutter:
  generate: true
  assets:
    - assets/
    - assets/countries/
    - assets/borders/
    - assets/flags/
    - assets/png100px/af.png
    - assets/png100px/al.png
    - assets/png100px/dz.png
    - assets/png100px/
    - assets/png250px/
    - assets/png1000px/
  uses-material-design: true
